-- =============================================================================
-- Quadro de histórias
--
-- As histórias de usuário do sistema, no formato de um quadro de trabalho:
-- cada cartão é uma história ("Eu… quero… para…") com os critérios de aceitação
-- em BDD, observações e uma lista de atividades (título + caixa de seleção).
--
-- Colunas: Backlog → Desenvolvimento → Teste → Homologação → Concluído.
--
-- A regra que manda aqui (RN-QDR-01 e RN-QDR-02, docs/08-produto/regras-de-negocio.md):
-- homologar é coisa de gente. Sem a sessão de uma pessoa — migração, SQL Editor,
-- automação, agente de código — o cartão só entra, sai e anda entre Backlog,
-- Desenvolvimento e Teste. Levar para Homologação ou Concluído, ou tirar de lá,
-- exige alguém que entrou no sistema; e Concluído só vem depois da Homologação.
-- A regra está no banco, e não só na tela, para valer por qualquer caminho.
--
-- Pode ser rodada de novo sem erro. Depende de 20260923120001_modulo_quadro.sql.
-- =============================================================================

-- 1. Tipo --------------------------------------------------------------------------

do $$
begin
  create type public.quadro_coluna as enum (
    'backlog',
    'desenvolvimento',
    'teste',
    'homologacao',
    'concluido'
  );
exception
  when duplicate_object then null;
end;
$$;

-- 2. Tabelas -----------------------------------------------------------------------

-- O "numero" é o identificador que aparece no cartão (H-07), como o ID de um
-- item de trabalho: estável, sequencial e nunca reaproveitado. As histórias da
-- documentação de produto mantêm o número que já tinham (H-01 a H-24).
create table if not exists public.historias (
  id uuid primary key default gen_random_uuid(),
  numero integer generated by default as identity,
  titulo text not null,
  tag text,
  eu text not null default '',
  quero text not null default '',
  para text not null default '',
  criterios text not null default '',
  observacoes text not null default '',
  coluna public.quadro_coluna not null default 'backlog',
  created_by uuid references public.users (id) on delete set null,
  updated_by uuid references public.users (id) on delete set null,
  created timestamptz not null default now(),
  updated timestamptz not null default now(),
  constraint historias_numero_key unique (numero),
  constraint historias_titulo_preenchido check (btrim(titulo) <> ''),
  constraint historias_titulo_tamanho check (char_length(titulo) <= 160),
  constraint historias_tag_tamanho check (tag is null or char_length(tag) <= 40)
);

create index if not exists historias_coluna_idx on public.historias (coluna, numero);

create table if not exists public.historias_atividades (
  id uuid primary key default gen_random_uuid(),
  historia uuid not null references public.historias (id) on delete cascade,
  titulo text not null,
  concluida boolean not null default false,
  ordem integer not null default 0,
  created_by uuid references public.users (id) on delete set null,
  updated_by uuid references public.users (id) on delete set null,
  created timestamptz not null default now(),
  updated timestamptz not null default now(),
  constraint historias_atividades_titulo_preenchido check (btrim(titulo) <> ''),
  constraint historias_atividades_titulo_tamanho check (char_length(titulo) <= 200)
);

create index if not exists historias_atividades_historia_idx
  on public.historias_atividades (historia, ordem);

-- 3. Homologação é coisa de gente (RN-QDR-01, RN-QDR-02) ----------------------------

create or replace function public.tg_proteger_homologacao()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_de public.quadro_coluna := case when tg_op = 'UPDATE' then old.coluna end;
begin
  if tg_op = 'UPDATE' and new.coluna is not distinct from old.coluna then
    return new;
  end if;

  if auth.uid() is null
     and (new.coluna in ('homologacao', 'concluido') or v_de in ('homologacao', 'concluido')) then
    raise exception
      'Só uma pessoa que entrou no sistema leva a história para Homologação ou Concluído, ou a tira de lá. Sem sessão, a história fica entre Backlog, Desenvolvimento e Teste.'
      using errcode = 'HA002';
  end if;

  if new.coluna = 'concluido' and v_de is distinct from 'homologacao' then
    raise exception
      'A história só vai para Concluído depois de passar pela Homologação. Mova para Homologação primeiro.'
      using errcode = 'HA002';
  end if;

  return new;
end;
$$;

revoke all on function public.tg_proteger_homologacao() from public, anon, authenticated;

drop trigger if exists proteger_homologacao on public.historias;
create trigger proteger_homologacao
  before insert or update of coluna on public.historias
  for each row execute function public.tg_proteger_homologacao();

-- 4. Carimbo, autoria e trilha -------------------------------------------------------
-- Mesmos gatilhos das outras tabelas. Só a história entra na trilha: marcar uma
-- atividade é miúdo demais para o feed do Início. É na trilha que fica quem
-- homologou — a mudança de coluna aparece com o "de → para" e o autor.

drop trigger if exists marcar_atualizacao on public.historias;
create trigger marcar_atualizacao before update on public.historias
  for each row execute function public.tg_marcar_atualizacao();

drop trigger if exists marcar_autoria on public.historias;
create trigger marcar_autoria before insert or update on public.historias
  for each row execute function public.tg_marcar_autoria();

drop trigger if exists registrar_log on public.historias;
create trigger registrar_log after insert or update or delete on public.historias
  for each row execute function public.tg_registrar_log('historias');

drop trigger if exists marcar_atualizacao on public.historias_atividades;
create trigger marcar_atualizacao before update on public.historias_atividades
  for each row execute function public.tg_marcar_atualizacao();

drop trigger if exists marcar_autoria on public.historias_atividades;
create trigger marcar_autoria before insert or update on public.historias_atividades
  for each row execute function public.tg_marcar_autoria();

-- A trilha ganha o "titulo" na lista de rótulos: sem ele, a história apareceria
-- no feed pelo começo do id. O resto da função é o da migração 20260919120004.
create or replace function public.tg_registrar_log()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_entidade text := tg_argv[0];
  v_linha    jsonb;
  v_acao     public.acao_auditoria;
  v_rotulo   text;
  v_pessoa   text;
  v_payload  jsonb;
begin
  if tg_op = 'DELETE' then
    v_acao := 'excluiu';
    v_linha := to_jsonb(old);
  elsif tg_op = 'UPDATE' then
    v_acao := 'editou';
    v_linha := to_jsonb(new);
  else
    v_acao := 'criou';
    v_linha := to_jsonb(new);
  end if;

  if v_entidade = 'permissoes' then
    select coalesce(nullif(u.name, ''), u.email) into v_pessoa
      from public.users u
     where u.id = (v_linha ->> 'usuario')::uuid;

    v_rotulo := format('%s — %s: %s',
      coalesce(v_pessoa, left(v_linha ->> 'usuario', 8)),
      v_linha ->> 'modulo',
      v_linha ->> 'nivel');
  else
    v_rotulo := coalesce(
      nullif(v_linha ->> 'nome', ''),
      nullif(v_linha ->> 'name', ''),
      nullif(v_linha ->> 'titulo', ''),
      nullif(v_linha ->> 'descricao', ''),
      nullif(v_linha ->> 'endereco', ''),
      nullif(v_linha ->> 'numero', ''),
      nullif(v_linha ->> 'arquivo_nome', ''),
      nullif(v_linha ->> 'email', ''),
      left(v_linha ->> 'id', 8)
    );
  end if;

  if tg_op = 'UPDATE' then
    select jsonb_object_agg(
             novo.key,
             jsonb_build_object('de', to_jsonb(old) -> novo.key, 'para', novo.value)
           )
      into v_payload
      from jsonb_each(to_jsonb(new)) as novo
     where novo.key not in ('updated', 'updated_by')
       and novo.value is distinct from to_jsonb(old) -> novo.key;
  end if;

  insert into public.logs_atividade (usuario, acao, entidade, registro_id, detalhes, payload)
  values (
    auth.uid(),
    v_acao,
    v_entidade,
    (v_linha ->> 'id')::uuid,
    format('%s %s "%s"', v_acao, v_entidade, v_rotulo),
    v_payload
  );

  return null;
end;
$$;

revoke all on function public.tg_registrar_log() from public, anon, authenticated;

-- 5. Quem vê e quem edita (RN-QDR-03) -------------------------------------------------
-- Ver exige visualização no módulo "quadro"; criar e editar, edição. Ninguém
-- exclui história — ela é a documentação do sistema; a que não vale mais volta
-- ao Backlog com a observação. A atividade, sim, pode ser excluída por quem edita.
-- Visitante sem login não vê nada, como no resto do sistema.

alter table public.historias enable row level security;
alter table public.historias_atividades enable row level security;

-- Sem DELETE nem TRUNCATE em historias: tentar excluir dá "permission denied",
-- e não um silencioso "nenhuma linha afetada".
revoke all on public.historias, public.historias_atividades from anon, authenticated;
grant select, insert, update on public.historias to authenticated;
grant select, insert, update, delete on public.historias_atividades to authenticated;

drop policy if exists historias_ver on public.historias;
create policy historias_ver on public.historias
  for select to authenticated using (public.pode_ver('quadro'));

drop policy if exists historias_criar on public.historias;
create policy historias_criar on public.historias
  for insert to authenticated with check (public.pode_editar('quadro'));

drop policy if exists historias_editar on public.historias;
create policy historias_editar on public.historias
  for update to authenticated
  using (public.pode_editar('quadro')) with check (public.pode_editar('quadro'));

drop policy if exists historias_atividades_ver on public.historias_atividades;
create policy historias_atividades_ver on public.historias_atividades
  for select to authenticated using (public.pode_ver('quadro'));

drop policy if exists historias_atividades_criar on public.historias_atividades;
create policy historias_atividades_criar on public.historias_atividades
  for insert to authenticated with check (public.pode_editar('quadro'));

drop policy if exists historias_atividades_editar on public.historias_atividades;
create policy historias_atividades_editar on public.historias_atividades
  for update to authenticated
  using (public.pode_editar('quadro')) with check (public.pode_editar('quadro'));

drop policy if exists historias_atividades_excluir on public.historias_atividades;
create policy historias_atividades_excluir on public.historias_atividades
  for delete to authenticated using (public.pode_editar('quadro'));

-- 6. Tempo real ----------------------------------------------------------------------
-- O quadro se atualiza sozinho quando outra pessoa move um cartão ou marca uma
-- atividade. Cada um só recebe o que a RLS deixa ler.

do $$
declare
  t text;
begin
  foreach t in array array['historias', 'historias_atividades'] loop
    if not exists (
      select 1 from pg_publication_tables
       where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end;
$$;
